name: feature_home
description: Home module.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  di:
    path: ../../di
  domain:
    path: ../../domain

  feature_record_list:
    path: ../record_list

dev_dependencies:
  flutter_lints: ^1.0.0