name: feature_settings
description: Settings module.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  di:
    path: ../../di
  domain:
    path: ../../domain

dev_dependencies:
  flutter_lints: ^1.0.0