name: storage
description: Storage module.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sqflite: ^2.0.2
  path: ^1.8.1
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

  core:
    path: ../core

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.1
  freezed: ^1.1.1