name: storage
description: Storage module.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sqflite: ^2.0.2
  path: ^1.8.1

dev_dependencies:
  flutter_lints: ^1.0.0